fix: install chrome when it is not already installed

diff --git a/config/files/usr/bin/check-chrome-version b/config/files/usr/bin/check-chrome-version
--- a/config/files/usr/bin/check-chrome-version
+++ b/config/files/usr/bin/check-chrome-version
@@ -1,21 +1,28 @@
 #!/bin/bash
 
 # Check currently layered Chrome version against the latest that the CI process found.
-# Todo: If needed, layer automatically with rpm-ostree and inform the user so
-# they'll know to reboot to get the latest Chrome goodness.
-set -eou pipefail
-CHROME_INSTALLED_VERSION=$(rpm -q --queryformat '%{VERSION}' google-chrome-stable)
+# Todo: Inform the user that Chrome has been updated so they'll know to reboot to get the 
+# latest Chrome goodness.
+if rpm -q google-chrome-stable > /dev/null; then
+    CHROME_INSTALLED_VERSION=$(rpm -q --queryformat '%{VERSION}' google-chrome-stable)
+else
+    CHROME_INSTALLED_VERSION="not installed" 
+fi
+
 CHROME_DOWNLOADED_VERSION=$(cat /usr/share/ublue-tr/chrome-workarounds/google-chrome-current-version)
 
 if [ "$CHROME_INSTALLED_VERSION" == "$CHROME_DOWNLOADED_VERSION" ]; then
     echo "Installed version of Google Chrome ($CHROME_INSTALLED_VERSION) is current"
 else
+    set -eou pipefail
     echo "Google Chrome needs an upgrade from $CHROME_INSTALLED_VERSION to $CHROME_DOWNLOADED_VERSION"
-    rpm-ostree remove google-chrome-stable
+    if [ "$CHROME_INSTALLED_VERSION" != "not installed" ]; then
+        rpm-ostree remove google-chrome-stable
+    fi
     rpm-ostree install /usr/share/ublue-tr/chrome-workarounds/google-chrome-stable_current_x86_64.rpm
-
     # The RPM installs the Google Chrome yum repo by default.  Apparently rpm-ostree will check this
-    # on an ordinary image update, and fail when it does so.  To avoid this, we'll disable it.
+    # on an ordinary image update, and fail when it does so.
+    # To avoid this, we'll disable it.
     sed -i '/enabled/d' /etc/yum.repos.d/google-chrome.repo 
     echo "enabled=0" >> /etc/yum.repos.d/google-chrome.repo
 fi
